title: Food Images Classifier
description: Classify food images using deep learning
about:


  This is a Food Images Classifier using Deep Learning built on top of Pytorch.


  The project was build by [Nidhin Pattaniyil](https://npatta01.github.io)
  and [Reshama Shaikh](https://reshamas.github.io).


  More info and the source code can he found below.


  - [Blog](https://reshamas.github.io/deploying-deep-learning-models-on-web-and-mobile/)    

  - [Web app](https://food-img-classifier.herokuapp.com)

  - [Video](https://www.youtube.com/watch?v=7d2qFLeYvRc)


  To try out this mobile app

    - [Expo](https://expo.io/@npatta01/food-app)

    - [Android](https://play.google.com/store/apps/details?id=com.rsnp.foodclassifier)

    - [iOS](https://itunes.apple.com/us/app/food-classifier/id1445356461?ls=1&mt=8)



  Check out our Manning liveProject [Deploying Deep Learning Model on Web and Mobile Applications Using TensorFlow](https://www.manning.com/liveproject/deploying-a-deep-learning-model-on-web-and-mobile-applications-using-tensorflow?utm_source=dataumbrella&utm_medium=affiliate&utm_campaign=liveproject_pattaniyil_11_24_20&a_aid=dataumbrella&a_bid=d66c1909)




code: https://github.com/npatta01/web-deep-learning-classifier

sampleImages:
  - name: lasagne
    url: https://upload.wikimedia.org/wikipedia/commons/b/ba/Lasagne_-_stonesoup.jpg
  - name: sushi
    url: https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg
  - name: waffles
    url: https://upload.wikimedia.org/wikipedia/commons/5/5b/Waffles_with_Strawberries.jpg
  - name: eggplant (not in training data)
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/1280px-Solanum_melongena_24_08_2012_%281%29.JPG
  - name: table (not in training & not a food)
    url: https://image.shutterstock.com/image-photo/brown-light-wooden-round-dining-260nw-588358070.jpg 
